
[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" }
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
option_as_alt = "Both"

[window.padding]
x = 5
y = 5

[font]
size = 20.0

[font.bold]
family = "VictorMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "VictorMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "Medium"

[general]

live_config_reload = true
import = ["~/.config/alacritty/themes/themes/solarized_dark.toml"]
